### PR TITLE
Internal console

### PR DESCRIPTION
**Pull request by GEEKiDoS**
#28

### CODE REVIEW

**Comment by GEEKiDoS** [comment]
command
cvarlist
cvar

This looks good for me.

**Comment by GEEKiDoS** [comment]
Use the '~` key not show output window now, Use shift+'~' to show output (Call of Duty style)
And the consolas unicode is intergated now(But the exe size is incrased)

**Comment by Ochii** [comment]
Sorry, I didn't mean to close it

**Comment by Ochii** [comment]
have you done any changes to imgui?

**Comment by GEEKiDoS** [comment]
> have you done any changes to imgui?

Yep, Check ImFont::RenderText of imgui_draw.cpp, I did some change to get ImGui rendering colored font using ^1 ^2 ^3 ^4 etc.

**Comment by GEEKiDoS** [comment]
@Ochii Please add this, Too lazy to make a commit, Just disable gameinput while console enabled to avoid some issue:
```
#include "tier2/tier2.h"
#include "inputsystem/iinputsystem.h"

void GameConsole::ToggleConsole( bool extend )
{
// ...
    // Disable gameinput while console enabled
    g_pInputSystem->EnableInput(!m_bShowConsole);
// ...
}
```

**Pull request merged**
