### PR TITLE
Auto login at start

### PR DESCRIPTION
**Pull request by GEEKiDoS**
#18

### CODE REVIEW

**Comment by GEEKiDoS** [comment]
And I noticed the latest code compiled in Debug will cause "Unable to load ui\cso2_ui.gfx" error like https://github.com/Ochii/cso2-launcher/issues/39

**Comment by Ochii** [comment]
The game tries to clear the password string after its used, but we did some patches that corrupted that action. I'll merge this then commit some patches to stop clearing the password. This allows bigger usernames but allows the password to live longer in memory. We'll figure a better fix for this later

**Comment by GEEKiDoS** [comment]
> The game tries to clear the password string after its used, but we did some patches that corrupted that action. I'll merge this then commit some patches to stop clearing the password. This allows bigger usernames but allows the password to live longer in memory. We'll figure a better fix for this later
> 
> EDIT: it's unrelated to the issue you're having @GEEKiDoS

And ascii char username(and password I guess?) will crashes the master server.

**Comment by Ochii** [comment]
the server treats the strings as utf8, and ascii should be supported by it

do you have an example on how to crash the server?

**Comment by GEEKiDoS** [comment]
> the server treats the strings as utf8, and ascii should be supported by it
> 
> do you have an example on how to crash the server?
I mean none-ascii like chinese(gbk I guess

, but my powershell page code is UTF8 qq 20190224032435)

```PS C:\Users\GEEKiDoS> .\launcher.exe -masterip 192.168.1.184 -enablecustom -lang schinese -username 你哥哥 -password 1234``` 

Then the server crashes while game try to login.
Log:
```
Error parsing packet: Error: The string's expected length is different from the one in the packet
buffer.js:207
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at new Buffer (buffer.js:182:17)
    at new User (E:\cso2-master-server\dist\user\user.js:28:28)
    at UserManager.addUser (E:\cso2-master-server\dist\user\usermanager.js:197:25)
    at UserManager.loginUser (E:\cso2-master-server\dist\user\usermanager.js:191:21)
    at UserManager.onLoginPacket (E:\cso2-master-server\dist\user\usermanager.js:39:30)
    at ServerInstance.onIncomingPacket (E:\cso2-master-server\dist\serverinstance.js:197:35)
    at ServerInstance.processPackets (E:\cso2-master-server\dist\serverinstance.js:174:18)
    at ServerInstance.onSocketData (E:\cso2-master-server\dist\serverinstance.js:165:14)
    at Socket.newSocket.on (E:\cso2-master-server\dist\serverinstance.js:85:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.8.8 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.8.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GEEKiDoS\AppData\Roaming\npm-cache\_logs\2019-02-23T19_27_10_726Z-debug.log
```

**Comment by Ochii** [comment]
That's the Valve's command line parser's fault. You can see in [this line](https://github.com/Ochii/cso2-launcher/pull/47/files#diff-04fa614240aa93bf195f126269383c7eR26), the result only supports ascii

**Comment by GEEKiDoS** [comment]
> That's the Valve's command line parser's fault. You can see in [this line](https://github.com/Ochii/cso2-launcher/pull/47/files#diff-04fa614240aa93bf195f126269383c7eR26), the result only supports ascii

So use the ```GetCommandLineW``` and I'm good to go?

**Comment by Ochii** [comment]
> 
> 
> > That's the Valve's command line parser's fault. You can see in [this line](https://github.com/Ochii/cso2-launcher/pull/47/files#diff-04fa614240aa93bf195f126269383c7eR26), the result only supports ascii
> 
> So use the `GetCommandLineW` and I'm good to go?

Something like that, I think we need to parse the command line arguments ourselves in order to support utf16 (I don't think we can support utf8) characters

**Comment by Ochii** [comment]
I'll merge this then we can think about that later

**Pull request merged**
